language: node_js
node_js:
  - '10'

branches:
  only:
  - source

cache:
  directories:
    - node_modules

script:
  - npm run build

deploy:
  local-dir: build
  skip-cleanup: true
  github-token: $GIT_TOKEN
  keep-history: true
  on:
    branch: master
