language: node_js
node_js:
  - '10'

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build

after_script:
  - git status
  - git config user.name "${GIT_USER_NAME}"
  - git config user.email "${GIT_USER_EMAIL}"
  - git add .
  - git commit -m "build app"
  - git push "https://${GIT_USER_NAME}@${GIT_TOKEN}${GIT_REPO}"

branches:
  only:
    - master