language: node_js
node_js:
  - '10'

cache:
  directories:
    - node_modules

script:
  - npm run build

deploy:
  provider: pages
  local-dit: build
  skip-cleanup: true
  githug-token: $GIT_TOKEN
  keep-history: true
  on:
    branch: master