language: node_js
node_js:
  - '10'

cache:
  directories:
    - node_modules

script:
  - npm run build

deploy:
  branch: master
  local-dir: build
  skip-cleanup: true
  github-token: $GIT_TOKEN
  keep-history: true